context:
  version: "0.40"

package:
  name: notmuch
  version: ${{ version }}

source:
  url: https://github.com/notmuch/notmuch/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8fd0c777ef054dc70aa1d7d46360d0608e35d7b49bfbfdaf510e00622081dd36

build:
  number: 0
  skip: win
  dynamic_linking:
    overlinking_behavior: error
    overdepending_behavior: error
  script:
    - >-
      PYTHON="$BUILD_PREFIX/bin/python" ./configure
      --prefix="$PREFIX" --libdir="$PREFIX/lib"
      --without-docs --without-emacs --without-desktop --without-ruby
    - make -j"$CPU_COUNT"
    - make install

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - gnupg
    - make
    - pkg-config
    - python
  host:
    - bash-completion
    - gmime
    - glib
    - sfsexp
    - talloc
    - xapian-core
    - zlib
  run:
    - gmime
    - libglib
    - libzlib
    - sfsexp
    - talloc
    - xapian-core

tests:
  - script:
      - notmuch --version
      - notmuch help
  - package_contents:
      bin:
        - notmuch
      lib:
        - notmuch
      include:
        - notmuch.h
      files:
        - share/bash-completion/completions/notmuch
        - share/zsh/site-functions/_notmuch
        - share/zsh/site-functions/_email-notmuch

about:
  homepage: https://notmuchmail.org/
  summary: Thread-based email index, search, and tagging.
  license: GPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING-GPL-3
  repository: https://github.com/notmuch/notmuch

extra:
  recipe-maintainers:
    - black-desk
